image: golang:latest

variables:
  # Please edit to your GitLab project
  VERSION: "v0.53.0"
  REPO_NAME: gitlab.com/kometchtech/mackerel-agent-plugins

stages:
  - build
  - deploy

build_job:
  stage: build
  only: 
    - master
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq devscripts debhelper fakeroot binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf
    - mkdir -p ${GOPATH}/src/$(dirname ${REPO_NAME})
    - ln -svf ${CI_PROJECT_DIR} ${GOPATH}/src/${REPO_NAME}
    - cd ${GOPATH}/src/${REPO_NAME}
    - make deps build deb
  artifacts:
    paths:
      - packaging/*.deb
    when: on_success

deploy_job:
  stage: deploy
  only:
    - master
  before_script:
    - go get -u github.com/aktau/github-release
  script:
    - export GITHUB_TOKEN=${GITHUB_TOKEN} github-release upload --user kometchtech --repo mackerel-agent-plugins --tag ${VERSION} --file packaging/*.deb
