image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/kometchtech/mackerel-agent-plugins

stages:
    - build

compile:
    stage: build
    script:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq rpm devscripts debhelper
      - cd $GOPATH/src/$REPO_NAME
      - make testdeps build
      - GOOS=linux GOARCH=arm64
      - cp build/mackerel-plugin packaging/deb-v2/debian/
      - cd packaging/deb-v2 && debuild --no-tgz-check -uc -us

    dependencies: []
    artifacts:
      untracked: true
      paths:
        - package/*.deb
