image: golang:latest

variables:
  VERSION: 'v0.53.0'
  REPO_NAME: 'gitlab.com/kometchtech/mackerel-agent-plugins'
  GIT_DEPTH: '1'

stages:
  - build
  - deploy

build_job:
  stage: build
  only:
    - master
  before_script:

    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq devscripts debhelper fakeroot binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf
    - mkdir -p ${GOPATH}/src/$(dirname ${REPO_NAME})
    - ln -svf ${CI_PROJECT_DIR} ${GOPATH}/src/${REPO_NAME}
  script:
    - cd ${GOPATH}/src/${REPO_NAME}
    - make deps build deb
  artifacts:
    paths:
      - packaging/*.deb
    when: on_success
    expire_in: 1d

deploy_job:
  stage: deploy
  only:
    - master
  before_script:
    - rm -f packaging/config.json packaging/*.orig.tar.gz
    - go get -u github.com/tcnksm/ghr
  script:
    - ghr -t ${GITHUB_TOKEN} -u kometchtech -r mackerel-agent-plugins -replace ${VERSION} packaging/
