image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/kometchtech/mackerel-agent-plugins

before_script:
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq rpm devscripts debhelper
  - mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
    - build

compile:
    stage: build
    before_script:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq rpm devscripts debhelper
      - mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
      - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
      - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME

    script:
      - make testdeps testconvention deb

    dependencies: []
    artifacts:
      untracked: true
      paths:
        - package/*.deb
