image: golang:1.13

variables:
  REPO_NAME: 'gitlab.com/kometchtech/mackerel-agent-plugins'
  GIT_DEPTH: '1'
  GO111MODULE: 'on'

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
      - /apt-cache
      - /go/src/github.com
      - /go/src/golang.org
      - /go/src/google.golang.org
      - /go/src/gopkg.in

stages:
  - build
  - test
  - deploy
  - cleanup

build_job:
  stage: build
  only:
    - master
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq devscripts debhelper rpm fakeroot binutils-aarch64-linux-gnu binutils-arm-linux-gnueabihf
    - mkdir -p ${GOPATH}/src/$(dirname ${REPO_NAME})
    - mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - ln -svf ${CI_PROJECT_DIR} ${GOPATH}/src/${REPO_NAME}
    - go get github.com/x-motemen/gobump/cmd/gobump
    - go get github.com/mackerelio/golib/cmd/mackerel-github-release
  script:
    - cd ${GOPATH}/src/${REPO_NAME}
    - make build rpm deb
    - mv /root/rpmbuild/RPMS/noarch/*.rpm packaging/
  artifacts:
    paths:
      - packaging/*.deb
      - packaging/*.rpm
    when: on_success
    expire_in: 1d

test_job:
  stage: test
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq redis-server memcached
    - mkdir -p ${GOPATH}/src/$(dirname ${REPO_NAME})
    - ln -svf ${CI_PROJECT_DIR} ${GOPATH}/src/${REPO_NAME}
  script:
    - cd ${GOPATH}/src/${REPO_NAME}
    - make lint cover testconvention
  allow_failure: false

deploy_job:
  stage: deploy
  cache: {}
  only:
    - master
  before_script:
    - VERSION=`cat ${CI_PROJECT_DIR}/Makefile | grep VERSION | head -n 1 | awk '{print $3}'`
    - rm -f packaging/config.json packaging/*.orig.tar.gz
    - go get -u github.com/tcnksm/ghr
  script:
    - ghr -t ${GITHUB_TOKEN} -u kometchtech -r mackerel-agent-plugins -replace v${VERSION} packaging/

cleanup:
  stage: cleanup
  cache:
    key: empty
    policy: pull
  script:
    - rm -rf /home/gitlab/cache/kometchtech/mackerel-agent-plugins/${CI_COMMIT_REF_NAME}*
