image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/kometchtech/mackerel-agent-plugins

stages:
    - build

compile:
    stage: build
    script:
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get install -y -qq rpm devscripts debhelper
      - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
      - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
      - cd $GOPATH/src/$REPO_NAME
      - make build build/mackerel-plugin testconvention deps deb

    artifacts:
      untracked: true
      paths:
        - package/*.deb
