---
name: test

on:
  push:
    branches:
    - master
    tags:
    - v*
  pull_request:
env:
  GO111MODULE: on
  DEBIAN_FRONTEND: noninteractive
jobs:
  test:
    strategy:
      matrix:
        go: ["1.14.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y redis-server
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - run: |
        make cover test
    - uses: shogo82148/actions-goveralls@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-profile: .profile.cov
        parallel: true
        job-number: ${{ strategy.job-index }}
  build:
    needs: [test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y rpm devscripts debhelper fakeroot crossbuild-essential-arm64
        mkdir -p ~/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - uses: actions/checkout@v2
    - run: make clean build rpm deb
    - uses: actions/upload-artifact@v2
      with:
        name: linux-build-artifacts
        path: |
          ~/rpmbuild/RPMS/*/*.rpm
          packaging/*.deb
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: linux-build-artifacts
        path: artifacts/
    - uses: mackerelio/staging-release-update-action@main
      if: github.ref == 'refs/heads/master'
      with:
        directory: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag: staging
    - uses: mackerelio/create-release-action@main
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        directory: artifacts/
        github-token: ${{ secrets.GITHUB_TOKEN }}
        tag-prefix: 'refs/tags/v'
        bump-up-branch-prefix: 'bump-version-'
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,action,eventName,ref,workflow,job,took
        username: mackerel-agent-plugins-release
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.MACKEREL_SLACK_WEBHOOK_URL }}
